
ALTER TABLE `user` MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE card MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE deck MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE deck_files MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE feedback MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE question MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE question_result MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE response_data MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE shared_decks MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE subscriber MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE subscription_plans MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE test MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE test_result MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE usage_records MODIFY COLUMN id INTEGER AUTO_INCREMENT;
ALTER TABLE user_settings MODIFY COLUMN id INTEGER AUTO_INCREMENT;