"""empty message

Revision ID: 05ec155fd61c
Revises: 6de60264f448
Create Date: 2023-06-26 10:22:10.840108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05ec155fd61c'
down_revision = '6de60264f448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=2500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.String(length=2500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
