"""empty message

Revision ID: 07c884d52307
Revises: 5f7fab200a8c
Create Date: 2023-03-07 18:26:46.362792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c884d52307'
down_revision = '5f7fab200a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('boc_2', sa.String(length=255), nullable=True),
    sa.Column('boc_3', sa.String(length=255), nullable=True),
    sa.Column('boc_4', sa.String(length=255), nullable=True),
    sa.Column('formula', sa.String(length=255), nullable=True),
    sa.Column('prompt_option', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('num_questions', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('result_reveal', sa.Boolean(), nullable=True),
    sa.Column('answer_reveal', sa.Boolean(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('taker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], )
    )
    op.create_table('question_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('taker', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['taker'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('question_result')
    op.drop_table('distribution')
    op.drop_table('test')
    op.drop_table('question')
    # ### end Alembic commands ###
