"""empty message

Revision ID: 0db9f10dc218
Revises: 07c884d52307
Create Date: 2023-03-07 20:03:41.230348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db9f10dc218'
down_revision = '07c884d52307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('q_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('q_order')
        batch_op.drop_column('q_type')

    # ### end Alembic commands ###
