"""empty message

Revision ID: 1c610ea8ffb3
Revises: aad16c6c47cb
Create Date: 2023-03-30 10:12:54.098167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c610ea8ffb3'
down_revision = 'aad16c6c47cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('item_quantity')
        batch_op.drop_column('item_number')

    # ### end Alembic commands ###
