"""empty message

Revision ID: 30ae25a6f4c0
Revises: b68f728f450b
Create Date: 2023-03-16 10:00:33.418977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ae25a6f4c0'
down_revision = 'b68f728f450b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subscription_plan_id')

    op.drop_table('usage_records')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
