"""empty message

Revision ID: 3797f5139f73
Revises: 9434313e4cf4
Create Date: 2023-03-28 13:29:24.858764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3797f5139f73'
down_revision = '9434313e4cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.drop_constraint('distribution_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['taker_id'], ['id'])

    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['taker'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['creator'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('distribution_ibfk_1', 'user', ['taker_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
