"""empty message

Revision ID: 404c0072b31f
Revises: f97074192c33
Create Date: 2023-03-04 15:29:16.755557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404c0072b31f'
down_revision = 'f97074192c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('receiver', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('public', sa.Integer(), nullable=True),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_decks')
    # ### end Alembic commands ###
