"""empty message

Revision ID: 493fa991be05
Revises: a44dbdfc130e
Create Date: 2023-06-14 15:39:24.081519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '493fa991be05'
down_revision = 'a44dbdfc130e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.alter_column('share_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['share_id'])

    with op.batch_alter_table('shared_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['share_id'])

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('share_id')

    with op.batch_alter_table('shared_decks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('share_id')

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('share_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
