"""empty message

Revision ID: 4c6e030870cb
Revises: bc64a9d3f10f
Create Date: 2023-03-08 19:17:51.364653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6e030870cb'
down_revision = 'bc64a9d3f10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('test_id_bug', 'test', ['test_id'], ['id'])
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_constraint('test_id_bug', type_='foreignkey')
        batch_op.drop_column('test_id')

    # ### end Alembic commands ###
