"""empty message

Revision ID: 4deeb150e53f
Revises: f794bf734924
Create Date: 2023-03-05 07:37:35.350495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4deeb150e53f'
down_revision = 'f794bf734924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prompt', sa.VARCHAR(), nullable=True),
    sa.Column('response', sa.VARCHAR(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.Column('time_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
