"""empty message

Revision ID: 504603b2de63
Revises: a890d9813d82
Create Date: 2023-06-12 21:51:09.901537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504603b2de63'
down_revision = 'a890d9813d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('guest')

    # ### end Alembic commands ###
