"""empty message

Revision ID: 5551ac416436
Revises: 693d83aff6ab
Create Date: 2023-03-03 15:56:06.847907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5551ac416436'
down_revision = '693d83aff6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_string', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_files', schema=None) as batch_op:
        batch_op.drop_column('text_string')

    # ### end Alembic commands ###
