"""empty message

Revision ID: 58d35345bc12
Revises: bc9ed60ea2e1
Create Date: 2023-03-05 07:54:55.676276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d35345bc12'
down_revision = 'bc9ed60ea2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_data', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
