"""empty message

Revision ID: 61f7f71fc43f
Revises: 3c32d72bbe9b
Create Date: 2023-03-08 09:46:22.834409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f7f71fc43f'
down_revision = '3c32d72bbe9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shuffle', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('shuffle')
        batch_op.drop_column('description')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
