"""empty message

Revision ID: 668c3d2e443e
Revises: 029b19ea144e
Create Date: 2023-04-17 17:39:39.139516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668c3d2e443e'
down_revision = '029b19ea144e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
