"""empty message

Revision ID: 693d83aff6ab
Revises: f1477a66c2cc
Create Date: 2023-03-01 21:20:23.395886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693d83aff6ab'
down_revision = 'f1477a66c2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_files',
    sa.Column('deck_file_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_file_id'], ['deck_files.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_files')
    # ### end Alembic commands ###
