"""empty message

Revision ID: 6de60264f448
Revises: 1c354cadbe49
Create Date: 2023-06-21 10:39:50.892931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de60264f448'
down_revision = '1c354cadbe49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_attributes', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
