"""empty message

Revision ID: 6e82e0b3a88a
Revises: 
Create Date: 2023-03-01 15:10:06.673531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e82e0b3a88a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=255), nullable=True, default='free'))
        batch_op.add_column(sa.Column('account_status', sa.String(length=255), nullable=True, default='active'))
        batch_op.add_column(sa.Column('account_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_expiration_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contacted_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dob')
        batch_op.drop_column('contacted_email')
        batch_op.drop_column('pic')
        batch_op.drop_column('gender')
        batch_op.drop_column('account_expiration_reason')
        batch_op.drop_column('account_expiration')
        batch_op.drop_column('account_status')
        batch_op.drop_column('account_type')
        batch_op.drop_column('time_accessed')
        batch_op.drop_column('time_created')
        batch_op.drop_column('external_type')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
