"""empty message

Revision ID: 76f69b1dceea
Revises: b623c49cafd9
Create Date: 2023-06-26 13:21:24.138160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f69b1dceea'
down_revision = 'b623c49cafd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_constraint('test_result_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('test_result_ibfk_3', 'test', ['test_id'], ['id'])

    # ### end Alembic commands ###
