"""empty message

Revision ID: 856e8e5865e3
Revises: 30ae25a6f4c0
Create Date: 2023-03-16 10:14:38.609134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856e8e5865e3'
down_revision = '30ae25a6f4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_subscription_plan_users', 'subscription_plans', ['subscription_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subscription_plan_id')

    # ### end Alembic commands ###
