"""empty message

Revision ID: 8e2012b89956
Revises: 856e8e5865e3
Create Date: 2023-03-16 10:17:39.390366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2012b89956'
down_revision = '856e8e5865e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_subscription_plan_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_sub_plan', 'subscription_plans', ['subscription_plan'], ['id'])
        batch_op.drop_column('subscription_plan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_subscription_plan_users', 'subscription_plans', ['subscription_plan_id'], ['id'])
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###
