"""empty message

Revision ID: 9b049121ac79
Revises: 668c3d2e443e
Create Date: 2023-04-17 17:46:58.748351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b049121ac79'
down_revision = '668c3d2e443e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.drop_column('invited_by_email')

    # ### end Alembic commands ###
