"""empty message

Revision ID: a44dbdfc130e
Revises: 504603b2de63
Create Date: 2023-06-14 13:05:16.919859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a44dbdfc130e'
down_revision = '504603b2de63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_response', schema=None) as batch_op:
        batch_op.alter_column('concepts',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('share_id')

    with op.batch_alter_table('cached_response', schema=None) as batch_op:
        batch_op.alter_column('concepts',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
