"""empty message

Revision ID: a890d9813d82
Revises: 
Create Date: 2023-06-12 21:48:27.212372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a890d9813d82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_type', sa.String(length=64), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_type', sa.String(length=64), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_accessed', sa.DateTime(), nullable=True),
    sa.Column('accessed_count', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('subtopic', sa.String(length=64), nullable=True),
    sa.Column('concepts', sa.String(length=64), nullable=True),
    sa.Column('difficulty', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_type', 'output_type', name='uix_1')
    )
    op.create_table('deck_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('sub_topic', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('concepts', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deck_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_attributes_time_created'), ['time_created'], unique=False)

    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('current_flashcard_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_flashcard_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2560), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_game',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('turns_as_main_player', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('game_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['game_answer.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty_cards_created', sa.Integer(), nullable=True))

    with op.batch_alter_table('job_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('input_details', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('extract_type', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_notification', schema=None) as batch_op:
        batch_op.drop_column('extract_type')
        batch_op.drop_column('input_details')
        batch_op.drop_column('state')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('qty_cards_created')

    op.drop_table('game_vote')
    op.drop_table('player_game')
    op.drop_table('game_answer')
    op.drop_table('game')
    with op.batch_alter_table('deck_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_attributes_time_created'))

    op.drop_table('deck_attributes')
    op.drop_table('cached_response')
    # ### end Alembic commands ###
