"""empty message

Revision ID: aad16c6c47cb
Revises: 3797f5139f73
Create Date: 2023-03-29 11:31:42.976379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad16c6c47cb'
down_revision = '3797f5139f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_user_study', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('new_user_decks', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('new_user_tests', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('new_user_cards', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('new_user_cards')
        batch_op.drop_column('new_user_tests')
        batch_op.drop_column('new_user_decks')
        batch_op.drop_column('new_user_study')

    # ### end Alembic commands ###
