"""empty message

Revision ID: b623c49cafd9
Revises: f7117219bf65
Create Date: 2023-06-26 13:19:53.882086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b623c49cafd9'
down_revision = 'f7117219bf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.drop_constraint('question_result_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('question_result_ibfk_3', 'test', ['test_id'], ['id'])

    # ### end Alembic commands ###
