"""empty message

Revision ID: b68f728f450b
Revises: 
Create Date: 2023-03-08 19:43:55.915849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68f728f450b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('boc_2', sa.String(length=255), nullable=True),
    sa.Column('boc_3', sa.String(length=255), nullable=True),
    sa.Column('boc_4', sa.String(length=255), nullable=True),
    sa.Column('formula', sa.String(length=255), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('sound', sa.String(length=255), nullable=True),
    sa.Column('boc_id', sa.Float(precision=10), nullable=True),
    sa.Column('box_id', sa.Float(precision=10), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('times_asked', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('times_correct_row', sa.Integer(), nullable=True),
    sa.Column('create_method', sa.String(length=255), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.Column('diff_lvl', sa.Float(precision=10), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('prompt_option', sa.String(length=255), nullable=True),
    sa.Column('prompt_option2', sa.String(length=255), nullable=True),
    sa.Column('trans_option', sa.String(length=255), nullable=True),
    sa.Column('len_option', sa.String(length=255), nullable=True),
    sa.Column('qmin_option', sa.String(length=255), nullable=True),
    sa.Column('qmax_option', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=50), nullable=True),
    sa.Column('file_type', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('text_string', sa.Text(), nullable=True),
    sa.Column('create_type', sa.String(length=50), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type_feedback', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_timestamp'), ['timestamp'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('boc_2', sa.String(length=255), nullable=True),
    sa.Column('boc_3', sa.String(length=255), nullable=True),
    sa.Column('boc_4', sa.String(length=255), nullable=True),
    sa.Column('formula', sa.String(length=255), nullable=True),
    sa.Column('prompt_option', sa.String(length=255), nullable=True),
    sa.Column('q_type', sa.String(length=50), nullable=True),
    sa.Column('q_order', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_data_timestamp'), ['timestamp'], unique=False)

    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name')
    )
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriber_timestamp'), ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_type', sa.String(length=255), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_accessed', sa.DateTime(), nullable=True),
    sa.Column('account_type', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.String(length=255), nullable=True),
    sa.Column('account_expiration', sa.DateTime(), nullable=True),
    sa.Column('account_expiration_reason', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('pic', sa.String(length=255), nullable=True),
    sa.Column('contacted_email', sa.Boolean(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('public', sa.Integer(), nullable=True),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.Column('create_method', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('times_accessed', sa.Integer(), nullable=True),
    sa.Column('access_date', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('sharer', sa.Integer(), nullable=True),
    sa.Column('share_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('receiver', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('public', sa.Integer(), nullable=True),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('num_questions', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('result_reveal', sa.Boolean(), nullable=True),
    sa.Column('answer_reveal', sa.Boolean(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('shuffle', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], )
    )
    op.create_table('cards_shared',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('shared_decks_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['shared_decks_id'], ['shared_decks.id'], )
    )
    op.create_table('distribution',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('taker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], )
    )
    op.create_table('question_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('taker', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['taker'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], )
    )
    op.create_table('source_files',
    sa.Column('deck_file_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_file_id'], ['deck_files.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], )
    )
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('taker', sa.Integer(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('blank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.ForeignKeyConstraint(['taker'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_result')
    op.drop_table('source_files')
    op.drop_table('questions')
    op.drop_table('question_result')
    op.drop_table('distribution')
    op.drop_table('cards_shared')
    op.drop_table('cards')
    op.drop_table('test')
    op.drop_table('shared_decks')
    op.drop_table('deck')
    op.drop_table('user')
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriber_timestamp'))

    op.drop_table('subscriber')
    with op.batch_alter_table('response_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_data_timestamp'))

    op.drop_table('response_data')
    op.drop_table('question')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_timestamp'))

    op.drop_table('feedback')
    op.drop_table('deck_files')
    op.drop_table('card')
    # ### end Alembic commands ###
