"""empty message

Revision ID: bc64a9d3f10f
Revises: a3a51e88d7e8
Create Date: 2023-03-08 19:13:05.797025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc64a9d3f10f'
down_revision = 'a3a51e88d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_constraint('test_id', type_='foreignkey')
        batch_op.drop_column('test')
        batch_op.drop_column('test_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('test', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('test_id', 'test', ['test'], ['id'])


    # ### end Alembic commands ###
