"""empty message

Revision ID: bc9ed60ea2e1
Revises: 4deeb150e53f
Create Date: 2023-03-05 07:49:33.766175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9ed60ea2e1'
down_revision = '4deeb150e53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_data_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_data_timestamp'))

    op.drop_table('response_data')
    # ### end Alembic commands ###
