"""empty message

Revision ID: d214411dbcc5
Revises: de0f0de18b5b
Create Date: 2023-03-20 14:51:30.829933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd214411dbcc5'
down_revision = 'de0f0de18b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('latest_roll_over', sa.DateTime(), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('latest_roll_over')
        batch_op.drop_column('subscription_start_date')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
