"""empty message

Revision ID: d46930235f89
Revises: de1bd0256308
Create Date: 2023-03-04 09:51:39.400629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46930235f89'
down_revision = 'de1bd0256308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_files', schema=None) as batch_op:
        batch_op.drop_column('time_created')
        batch_op.drop_column('create_type')

    # ### end Alembic commands ###
