"""empty message

Revision ID: de1bd0256308
Revises: e4d07fc6025b
Create Date: 2023-03-03 18:36:03.249186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1bd0256308'
down_revision = 'e4d07fc6025b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
