"""empty message

Revision ID: e2803d5721e0
Revises: 6e82e0b3a88a
Create Date: 2023-03-01 17:20:22.284047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2803d5721e0'
down_revision = '6e82e0b3a88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=50), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('file_size'),
    sa.UniqueConstraint('file_type')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prompt_option', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prompt_option2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trans_option', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('len_option', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qmin_option', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qmax_option', sa.String(length=255), nullable=True))

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('accepted')
        batch_op.drop_column('shared')
        batch_op.drop_column('topic')
        batch_op.drop_column('subject')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('qmax_option')
        batch_op.drop_column('qmin_option')
        batch_op.drop_column('len_option')
        batch_op.drop_column('trans_option')
        batch_op.drop_column('prompt_option2')
        batch_op.drop_column('prompt_option')
        batch_op.drop_column('topic')
        batch_op.drop_column('subject')

    op.drop_table('deck_files')
    # ### end Alembic commands ###
