"""empty message

Revision ID: e4d07fc6025b
Revises: 5551ac416436
Create Date: 2023-03-03 15:59:17.602284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d07fc6025b'
down_revision = '5551ac416436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_files', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_files', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
