"""empty message

Revision ID: f20c3e28dea7
Revises: 
Create Date: 2023-09-16 13:44:45.012338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20c3e28dea7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint('cards_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'deck', ['deck_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('deck_relationships', schema=None) as batch_op:
        batch_op.drop_constraint('deck_relationships_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('deck_relationships_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'deck', ['parent_deck'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'deck', ['child_deck'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_constraint('source_files_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'deck', ['deck_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('source_files_ibfk_2', 'deck', ['deck_id'], ['id'])

    with op.batch_alter_table('deck_relationships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deck_relationships_ibfk_2', 'deck', ['parent_deck'], ['id'])
        batch_op.create_foreign_key('deck_relationships_ibfk_1', 'deck', ['child_deck'], ['id'])

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cards_ibfk_2', 'deck', ['deck_id'], ['id'])

    # ### end Alembic commands ###
