"""empty message

Revision ID: f2c36ec28a20
Revises: cd1389ac1dbb
Create Date: 2023-03-08 18:53:45.372215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c36ec28a20'
down_revision = 'cd1389ac1dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('test_id', 'test', ['test'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_constraint('test_id', type_='foreignkey')
        batch_op.drop_column('test')

    # ### end Alembic commands ###
