"""empty message

Revision ID: f4c287aa27e7
Revises: 
Create Date: 2023-03-26 13:39:42.961398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4c287aa27e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('boc_4',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('boc_4',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
