"""empty message

Revision ID: f7bebc8a5341
Revises: 8e2012b89956
Create Date: 2023-03-16 12:35:06.151127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bebc8a5341'
down_revision = '8e2012b89956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('latest_roll_over', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('latest_roll_over')
        batch_op.drop_column('subscription_start_date')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
