"""empty message

Revision ID: f97074192c33
Revises: d46930235f89
Create Date: 2023-03-04 14:05:22.738953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97074192c33'
down_revision = 'd46930235f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sharer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('share_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('share_date')
        batch_op.drop_column('sharer')

    # ### end Alembic commands ###
