"""empty message

Revision ID: fb83669b8e03
Revises: 404c0072b31f
Create Date: 2023-03-04 15:35:22.755861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb83669b8e03'
down_revision = '404c0072b31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards_shared',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('shared_decks_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['shared_decks_id'], ['shared_decks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards_shared')
    # ### end Alembic commands ###
